name: simplerecon
channels:
  - default
  - pytorch
  - conda-forge
dependencies:
  - clang=15.0.7
  - llvm-openmp=15.0.7
  - pillow # image op
  - tensorboard # logging
  - matplotlib # plotting
  - pip

